<?php
/**
 * CreateOperatingEnvelopeWithNmiRequestDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CreateOperatingEnvelopeWithNmiRequestDto Class Doc Comment
 *
 * @category Class
 * @description Create Operting Envelope request
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreateOperatingEnvelopeWithNmiRequestDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateOperatingEnvelopeWithNmiRequestDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'event_id' => 'string',
        'start_at_utc' => '\DateTime',
        'end_at_utc' => '\DateTime',
        'max_import_power_w' => 'int',
        'max_export_power_w' => 'int',
        'max_discharge_power_w' => 'int',
        'max_charge_power_w' => 'int',
        'max_generation_power_va' => 'int',
        'nmi' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'event_id' => null,
        'start_at_utc' => 'date-time',
        'end_at_utc' => 'date-time',
        'max_import_power_w' => 'int32',
        'max_export_power_w' => 'int32',
        'max_discharge_power_w' => 'int32',
        'max_charge_power_w' => 'int32',
        'max_generation_power_va' => 'int32',
        'nmi' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'event_id' => 'EventId',
        'start_at_utc' => 'StartAtUtc',
        'end_at_utc' => 'EndAtUtc',
        'max_import_power_w' => 'MaxImportPowerW',
        'max_export_power_w' => 'MaxExportPowerW',
        'max_discharge_power_w' => 'MaxDischargePowerW',
        'max_charge_power_w' => 'MaxChargePowerW',
        'max_generation_power_va' => 'MaxGenerationPowerVA',
        'nmi' => 'Nmi'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'event_id' => 'setEventId',
        'start_at_utc' => 'setStartAtUtc',
        'end_at_utc' => 'setEndAtUtc',
        'max_import_power_w' => 'setMaxImportPowerW',
        'max_export_power_w' => 'setMaxExportPowerW',
        'max_discharge_power_w' => 'setMaxDischargePowerW',
        'max_charge_power_w' => 'setMaxChargePowerW',
        'max_generation_power_va' => 'setMaxGenerationPowerVa',
        'nmi' => 'setNmi'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'event_id' => 'getEventId',
        'start_at_utc' => 'getStartAtUtc',
        'end_at_utc' => 'getEndAtUtc',
        'max_import_power_w' => 'getMaxImportPowerW',
        'max_export_power_w' => 'getMaxExportPowerW',
        'max_discharge_power_w' => 'getMaxDischargePowerW',
        'max_charge_power_w' => 'getMaxChargePowerW',
        'max_generation_power_va' => 'getMaxGenerationPowerVa',
        'nmi' => 'getNmi'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['event_id'] = isset($data['event_id']) ? $data['event_id'] : null;
        $this->container['start_at_utc'] = isset($data['start_at_utc']) ? $data['start_at_utc'] : null;
        $this->container['end_at_utc'] = isset($data['end_at_utc']) ? $data['end_at_utc'] : null;
        $this->container['max_import_power_w'] = isset($data['max_import_power_w']) ? $data['max_import_power_w'] : null;
        $this->container['max_export_power_w'] = isset($data['max_export_power_w']) ? $data['max_export_power_w'] : null;
        $this->container['max_discharge_power_w'] = isset($data['max_discharge_power_w']) ? $data['max_discharge_power_w'] : null;
        $this->container['max_charge_power_w'] = isset($data['max_charge_power_w']) ? $data['max_charge_power_w'] : null;
        $this->container['max_generation_power_va'] = isset($data['max_generation_power_va']) ? $data['max_generation_power_va'] : null;
        $this->container['nmi'] = isset($data['nmi']) ? $data['nmi'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets event_id
     *
     * @return string
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param string $event_id Event Id. It may be shared between operating envelopes.   Maximum length: 128 characters.
     *
     * @return $this
     */
    public function setEventId($event_id)
    {
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets start_at_utc
     *
     * @return \DateTime
     */
    public function getStartAtUtc()
    {
        return $this->container['start_at_utc'];
    }

    /**
     * Sets start_at_utc
     *
     * @param \DateTime $start_at_utc Start
     *
     * @return $this
     */
    public function setStartAtUtc($start_at_utc)
    {
        $this->container['start_at_utc'] = $start_at_utc;

        return $this;
    }

    /**
     * Gets end_at_utc
     *
     * @return \DateTime
     */
    public function getEndAtUtc()
    {
        return $this->container['end_at_utc'];
    }

    /**
     * Sets end_at_utc
     *
     * @param \DateTime $end_at_utc End
     *
     * @return $this
     */
    public function setEndAtUtc($end_at_utc)
    {
        $this->container['end_at_utc'] = $end_at_utc;

        return $this;
    }

    /**
     * Gets max_import_power_w
     *
     * @return int
     */
    public function getMaxImportPowerW()
    {
        return $this->container['max_import_power_w'];
    }

    /**
     * Sets max_import_power_w
     *
     * @param int $max_import_power_w Max Import Power W
     *
     * @return $this
     */
    public function setMaxImportPowerW($max_import_power_w)
    {
        $this->container['max_import_power_w'] = $max_import_power_w;

        return $this;
    }

    /**
     * Gets max_export_power_w
     *
     * @return int
     */
    public function getMaxExportPowerW()
    {
        return $this->container['max_export_power_w'];
    }

    /**
     * Sets max_export_power_w
     *
     * @param int $max_export_power_w Max Export Power W
     *
     * @return $this
     */
    public function setMaxExportPowerW($max_export_power_w)
    {
        $this->container['max_export_power_w'] = $max_export_power_w;

        return $this;
    }

    /**
     * Gets max_discharge_power_w
     *
     * @return int
     */
    public function getMaxDischargePowerW()
    {
        return $this->container['max_discharge_power_w'];
    }

    /**
     * Sets max_discharge_power_w
     *
     * @param int $max_discharge_power_w Max Discharge Power in W
     *
     * @return $this
     */
    public function setMaxDischargePowerW($max_discharge_power_w)
    {
        $this->container['max_discharge_power_w'] = $max_discharge_power_w;

        return $this;
    }

    /**
     * Gets max_charge_power_w
     *
     * @return int
     */
    public function getMaxChargePowerW()
    {
        return $this->container['max_charge_power_w'];
    }

    /**
     * Sets max_charge_power_w
     *
     * @param int $max_charge_power_w Max Charge Power in W
     *
     * @return $this
     */
    public function setMaxChargePowerW($max_charge_power_w)
    {
        $this->container['max_charge_power_w'] = $max_charge_power_w;

        return $this;
    }

    /**
     * Gets max_generation_power_va
     *
     * @return int
     */
    public function getMaxGenerationPowerVa()
    {
        return $this->container['max_generation_power_va'];
    }

    /**
     * Sets max_generation_power_va
     *
     * @param int $max_generation_power_va Max Generation Power in VA
     *
     * @return $this
     */
    public function setMaxGenerationPowerVa($max_generation_power_va)
    {
        $this->container['max_generation_power_va'] = $max_generation_power_va;

        return $this;
    }

    /**
     * Gets nmi
     *
     * @return string
     */
    public function getNmi()
    {
        return $this->container['nmi'];
    }

    /**
     * Sets nmi
     *
     * @param string $nmi SiteId
     *
     * @return $this
     */
    public function setNmi($nmi)
    {
        $this->container['nmi'] = $nmi;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
