<?php
/**
 * InverterModeValuePublic
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * InverterModeValuePublic Class Doc Comment
 *
 * @category Class
 * @description Inverter power modes
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InverterModeValuePublic
{
    /**
     * Possible values of this enum
     */
    const NO_MODE = 'NoMode';
    const AUTO = 'Auto';
    const CHARGE_BATTERY = 'ChargeBattery';
    const DISCHARGE_BATTERY = 'DischargeBattery';
    const IMPORT_POWER = 'ImportPower';
    const EXPORT_POWER = 'ExportPower';
    const CONSERVE = 'Conserve';
    const OFFGRID = 'Offgrid';
    const HIBERNATE = 'Hibernate';
    const BUY_POWER = 'BuyPower';
    const SELL_POWER = 'SellPower';
    const FORCE_CHARGE_BATTERY = 'ForceChargeBattery';
    const FORCE_DISCHARGE_BATTERY = 'ForceDischargeBattery';
    const STOP = 'Stop';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NO_MODE
            self::AUTO
            self::CHARGE_BATTERY
            self::DISCHARGE_BATTERY
            self::IMPORT_POWER
            self::EXPORT_POWER
            self::CONSERVE
            self::OFFGRID
            self::HIBERNATE
            self::BUY_POWER
            self::SELL_POWER
            self::FORCE_CHARGE_BATTERY
            self::FORCE_DISCHARGE_BATTERY
            self::STOP
        ];
    }
}
