<?php
/**
 * JobRunStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * JobRunStatus Class Doc Comment
 *
 * @category Class
 * @description Status
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobRunStatus
{
    /**
     * Possible values of this enum
     */
    const QUEUED = 'Queued';
    const PENDING = 'Pending';
    const IN_PROGRESS = 'InProgress';
    const FAILED = 'Failed';
    const COMPLETED = 'Completed';
    const COMPLETE_WITH_ERROR = 'CompleteWithError';
    const DELETED = 'Deleted';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::QUEUED
            self::PENDING
            self::IN_PROGRESS
            self::FAILED
            self::COMPLETED
            self::COMPLETE_WITH_ERROR
            self::DELETED
        ];
    }
}
