<?php
/**
 * OperatingEnvelopeStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * OperatingEnvelopeStatus Class Doc Comment
 *
 * @category Class
 * @description Possible statuses of operating envelopes
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OperatingEnvelopeStatus
{
    /**
     * Possible values of this enum
     */
    const OLD_UNREPORTED = 'OldUnreported';
    const _NEW = 'New';
    const SCHEDULED = 'Scheduled';
    const CANCELLED = 'Cancelled';
    const REPORT_STARTED = 'ReportStarted';
    const REPORT_FINISHED = 'ReportFinished';
    const SUPERSEDED_PRIOR_TO_START = 'SupersededPriorToStart';
    const FUTURE_SUPERSEDE = 'FutureSupersede';
    const SUPERSEDED_AFTER_START = 'SupersededAfterStart';
    const FUTURE_CANCEL = 'FutureCancel';
    const CANCELLED_AFTER_START = 'CancelledAfterStart';
    const REJECTED_PAST_EVENT = 'RejectedPastEvent';
    const REJECT_SUPERSEDED = 'RejectSuperseded';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OLD_UNREPORTED
            self::_NEW
            self::SCHEDULED
            self::CANCELLED
            self::REPORT_STARTED
            self::REPORT_FINISHED
            self::SUPERSEDED_PRIOR_TO_START
            self::FUTURE_SUPERSEDE
            self::SUPERSEDED_AFTER_START
            self::FUTURE_CANCEL
            self::CANCELLED_AFTER_START
            self::REJECTED_PAST_EVENT
            self::REJECT_SUPERSEDED
        ];
    }
}
