<?php
/**
 * PanelDirection
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * PanelDirection Class Doc Comment
 *
 * @category Class
 * @description 8 supported panel directions and None for unknown/unavailable
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PanelDirection
{
    /**
     * Possible values of this enum
     */
    const NONE = 'None';
    const N = 'N';
    const E = 'E';
    const W = 'W';
    const S = 'S';
    const NE = 'NE';
    const NW = 'NW';
    const SE = 'SE';
    const SW = 'SW';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE
            self::N
            self::E
            self::W
            self::S
            self::NE
            self::NW
            self::SE
            self::SW
        ];
    }
}
