<?php
/**
 * ScheduleDays
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ScheduleDays Class Doc Comment
 *
 * @category Class
 * @description Schedule days flags. Bit flags.  Examples: A. a) 1 or b) \&quot;Sunday\&quot; means Sunday B. a) 5 or b) \&quot;Monday, Wednesday\&quot; means Monday and Wednesday C. a) 62 or b) \&quot;Weekdays\&quot; or c) \&quot;Monday, Tuesday, Wednesday, Thursday, Friday\&quot; means Monday to Fridays inclusive.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduleDays
{
    /**
     * Possible values of this enum
     */
    const NEVER = 'Never';
    const SUNDAY = 'Sunday';
    const MONDAY = 'Monday';
    const TUESDAY = 'Tuesday';
    const WEDNESDAY = 'Wednesday';
    const THURSDAY = 'Thursday';
    const FRIDAY = 'Friday';
    const WEEKDAYS = 'Weekdays';
    const SATURDAY = 'Saturday';
    const WEEKENDS = 'Weekends';
    const EVERYDAY = 'Everyday';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NEVER
            self::SUNDAY
            self::MONDAY
            self::TUESDAY
            self::WEDNESDAY
            self::THURSDAY
            self::FRIDAY
            self::WEEKDAYS
            self::SATURDAY
            self::WEEKENDS
            self::EVERYDAY
        ];
    }
}
