<?php
/**
 * SiteDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SiteDetails Class Doc Comment
 *
 * @category Class
 * @description Site info
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SiteDetails implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SiteDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'generation_hard_limit_va' => 'float',
        'generation_soft_limit_va' => 'float',
        'export_hard_limitk_w' => 'float',
        'export_hard_limit_w' => 'float',
        'export_soft_limitk_w' => 'float',
        'export_soft_limit_w' => 'float',
        'site_export_limitk_w' => 'float',
        'battery_max_charge_powerk_w' => 'float',
        'battery_max_discharge_powerk_w' => 'float',
        'battery_capacityk_wh' => 'float',
        'usable_battery_capacityk_wh' => 'float',
        'panel_model' => 'string',
        'panel_sizek_w' => 'float',
        'system_type' => 'string',
        'inverter_max_export_powerk_w' => 'float',
        'inverter_max_import_powerk_w' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'generation_hard_limit_va' => 'decimal',
        'generation_soft_limit_va' => 'decimal',
        'export_hard_limitk_w' => 'decimal',
        'export_hard_limit_w' => 'decimal',
        'export_soft_limitk_w' => 'decimal',
        'export_soft_limit_w' => 'decimal',
        'site_export_limitk_w' => 'decimal',
        'battery_max_charge_powerk_w' => 'decimal',
        'battery_max_discharge_powerk_w' => 'decimal',
        'battery_capacityk_wh' => 'decimal',
        'usable_battery_capacityk_wh' => 'decimal',
        'panel_model' => null,
        'panel_sizek_w' => 'decimal',
        'system_type' => null,
        'inverter_max_export_powerk_w' => 'decimal',
        'inverter_max_import_powerk_w' => 'decimal'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'generation_hard_limit_va' => 'GenerationHardLimitVA',
        'generation_soft_limit_va' => 'GenerationSoftLimitVA',
        'export_hard_limitk_w' => 'ExportHardLimitkW',
        'export_hard_limit_w' => 'ExportHardLimitW',
        'export_soft_limitk_w' => 'ExportSoftLimitkW',
        'export_soft_limit_w' => 'ExportSoftLimitW',
        'site_export_limitk_w' => 'SiteExportLimitkW',
        'battery_max_charge_powerk_w' => 'BatteryMaxChargePowerkW',
        'battery_max_discharge_powerk_w' => 'BatteryMaxDischargePowerkW',
        'battery_capacityk_wh' => 'BatteryCapacitykWh',
        'usable_battery_capacityk_wh' => 'UsableBatteryCapacitykWh',
        'panel_model' => 'PanelModel',
        'panel_sizek_w' => 'PanelSizekW',
        'system_type' => 'SystemType',
        'inverter_max_export_powerk_w' => 'InverterMaxExportPowerkW',
        'inverter_max_import_powerk_w' => 'InverterMaxImportPowerkW'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'generation_hard_limit_va' => 'setGenerationHardLimitVa',
        'generation_soft_limit_va' => 'setGenerationSoftLimitVa',
        'export_hard_limitk_w' => 'setExportHardLimitkW',
        'export_hard_limit_w' => 'setExportHardLimitW',
        'export_soft_limitk_w' => 'setExportSoftLimitkW',
        'export_soft_limit_w' => 'setExportSoftLimitW',
        'site_export_limitk_w' => 'setSiteExportLimitkW',
        'battery_max_charge_powerk_w' => 'setBatteryMaxChargePowerkW',
        'battery_max_discharge_powerk_w' => 'setBatteryMaxDischargePowerkW',
        'battery_capacityk_wh' => 'setBatteryCapacitykWh',
        'usable_battery_capacityk_wh' => 'setUsableBatteryCapacitykWh',
        'panel_model' => 'setPanelModel',
        'panel_sizek_w' => 'setPanelSizekW',
        'system_type' => 'setSystemType',
        'inverter_max_export_powerk_w' => 'setInverterMaxExportPowerkW',
        'inverter_max_import_powerk_w' => 'setInverterMaxImportPowerkW'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'generation_hard_limit_va' => 'getGenerationHardLimitVa',
        'generation_soft_limit_va' => 'getGenerationSoftLimitVa',
        'export_hard_limitk_w' => 'getExportHardLimitkW',
        'export_hard_limit_w' => 'getExportHardLimitW',
        'export_soft_limitk_w' => 'getExportSoftLimitkW',
        'export_soft_limit_w' => 'getExportSoftLimitW',
        'site_export_limitk_w' => 'getSiteExportLimitkW',
        'battery_max_charge_powerk_w' => 'getBatteryMaxChargePowerkW',
        'battery_max_discharge_powerk_w' => 'getBatteryMaxDischargePowerkW',
        'battery_capacityk_wh' => 'getBatteryCapacitykWh',
        'usable_battery_capacityk_wh' => 'getUsableBatteryCapacitykWh',
        'panel_model' => 'getPanelModel',
        'panel_sizek_w' => 'getPanelSizekW',
        'system_type' => 'getSystemType',
        'inverter_max_export_powerk_w' => 'getInverterMaxExportPowerkW',
        'inverter_max_import_powerk_w' => 'getInverterMaxImportPowerkW'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['generation_hard_limit_va'] = isset($data['generation_hard_limit_va']) ? $data['generation_hard_limit_va'] : null;
        $this->container['generation_soft_limit_va'] = isset($data['generation_soft_limit_va']) ? $data['generation_soft_limit_va'] : null;
        $this->container['export_hard_limitk_w'] = isset($data['export_hard_limitk_w']) ? $data['export_hard_limitk_w'] : null;
        $this->container['export_hard_limit_w'] = isset($data['export_hard_limit_w']) ? $data['export_hard_limit_w'] : null;
        $this->container['export_soft_limitk_w'] = isset($data['export_soft_limitk_w']) ? $data['export_soft_limitk_w'] : null;
        $this->container['export_soft_limit_w'] = isset($data['export_soft_limit_w']) ? $data['export_soft_limit_w'] : null;
        $this->container['site_export_limitk_w'] = isset($data['site_export_limitk_w']) ? $data['site_export_limitk_w'] : null;
        $this->container['battery_max_charge_powerk_w'] = isset($data['battery_max_charge_powerk_w']) ? $data['battery_max_charge_powerk_w'] : null;
        $this->container['battery_max_discharge_powerk_w'] = isset($data['battery_max_discharge_powerk_w']) ? $data['battery_max_discharge_powerk_w'] : null;
        $this->container['battery_capacityk_wh'] = isset($data['battery_capacityk_wh']) ? $data['battery_capacityk_wh'] : null;
        $this->container['usable_battery_capacityk_wh'] = isset($data['usable_battery_capacityk_wh']) ? $data['usable_battery_capacityk_wh'] : null;
        $this->container['panel_model'] = isset($data['panel_model']) ? $data['panel_model'] : null;
        $this->container['panel_sizek_w'] = isset($data['panel_sizek_w']) ? $data['panel_sizek_w'] : null;
        $this->container['system_type'] = isset($data['system_type']) ? $data['system_type'] : null;
        $this->container['inverter_max_export_powerk_w'] = isset($data['inverter_max_export_powerk_w']) ? $data['inverter_max_export_powerk_w'] : null;
        $this->container['inverter_max_import_powerk_w'] = isset($data['inverter_max_import_powerk_w']) ? $data['inverter_max_import_powerk_w'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets generation_hard_limit_va
     *
     * @return float
     */
    public function getGenerationHardLimitVa()
    {
        return $this->container['generation_hard_limit_va'];
    }

    /**
     * Sets generation_hard_limit_va
     *
     * @param float $generation_hard_limit_va Gets generation hard limit. Unit: volt amps
     *
     * @return $this
     */
    public function setGenerationHardLimitVa($generation_hard_limit_va)
    {
        $this->container['generation_hard_limit_va'] = $generation_hard_limit_va;

        return $this;
    }

    /**
     * Gets generation_soft_limit_va
     *
     * @return float
     */
    public function getGenerationSoftLimitVa()
    {
        return $this->container['generation_soft_limit_va'];
    }

    /**
     * Sets generation_soft_limit_va
     *
     * @param float $generation_soft_limit_va Gets generation soft limit. Unit: volt amps
     *
     * @return $this
     */
    public function setGenerationSoftLimitVa($generation_soft_limit_va)
    {
        $this->container['generation_soft_limit_va'] = $generation_soft_limit_va;

        return $this;
    }

    /**
     * Gets export_hard_limitk_w
     *
     * @return float
     */
    public function getExportHardLimitkW()
    {
        return $this->container['export_hard_limitk_w'];
    }

    /**
     * Sets export_hard_limitk_w
     *
     * @param float $export_hard_limitk_w Gets export hard limit. Unit: kilowatt
     *
     * @return $this
     */
    public function setExportHardLimitkW($export_hard_limitk_w)
    {
        $this->container['export_hard_limitk_w'] = $export_hard_limitk_w;

        return $this;
    }

    /**
     * Gets export_hard_limit_w
     *
     * @return float
     */
    public function getExportHardLimitW()
    {
        return $this->container['export_hard_limit_w'];
    }

    /**
     * Sets export_hard_limit_w
     *
     * @param float $export_hard_limit_w [Deprecated] Gets export hard limit. Despite the name the unit is kilowatt. ExportHardLimitkW
     *
     * @return $this
     */
    public function setExportHardLimitW($export_hard_limit_w)
    {
        $this->container['export_hard_limit_w'] = $export_hard_limit_w;

        return $this;
    }

    /**
     * Gets export_soft_limitk_w
     *
     * @return float
     */
    public function getExportSoftLimitkW()
    {
        return $this->container['export_soft_limitk_w'];
    }

    /**
     * Sets export_soft_limitk_w
     *
     * @param float $export_soft_limitk_w Gets export soft limit. Unit: kilowatt
     *
     * @return $this
     */
    public function setExportSoftLimitkW($export_soft_limitk_w)
    {
        $this->container['export_soft_limitk_w'] = $export_soft_limitk_w;

        return $this;
    }

    /**
     * Gets export_soft_limit_w
     *
     * @return float
     */
    public function getExportSoftLimitW()
    {
        return $this->container['export_soft_limit_w'];
    }

    /**
     * Sets export_soft_limit_w
     *
     * @param float $export_soft_limit_w [Deprecated] Gets export soft limit. Despite the name the unit is kilowatt. ExportSoftLimitkW
     *
     * @return $this
     */
    public function setExportSoftLimitW($export_soft_limit_w)
    {
        $this->container['export_soft_limit_w'] = $export_soft_limit_w;

        return $this;
    }

    /**
     * Gets site_export_limitk_w
     *
     * @return float
     */
    public function getSiteExportLimitkW()
    {
        return $this->container['site_export_limitk_w'];
    }

    /**
     * Sets site_export_limitk_w
     *
     * @param float $site_export_limitk_w Gets site export limit. Unit: kilowatt
     *
     * @return $this
     */
    public function setSiteExportLimitkW($site_export_limitk_w)
    {
        $this->container['site_export_limitk_w'] = $site_export_limitk_w;

        return $this;
    }

    /**
     * Gets battery_max_charge_powerk_w
     *
     * @return float
     */
    public function getBatteryMaxChargePowerkW()
    {
        return $this->container['battery_max_charge_powerk_w'];
    }

    /**
     * Sets battery_max_charge_powerk_w
     *
     * @param float $battery_max_charge_powerk_w Gets the static 'nominal' maximum charge power theoretically supported by the site's inverter and batteries. The actual \"at this point in time\" value may be lower. Unit: kilowatt
     *
     * @return $this
     */
    public function setBatteryMaxChargePowerkW($battery_max_charge_powerk_w)
    {
        $this->container['battery_max_charge_powerk_w'] = $battery_max_charge_powerk_w;

        return $this;
    }

    /**
     * Gets battery_max_discharge_powerk_w
     *
     * @return float
     */
    public function getBatteryMaxDischargePowerkW()
    {
        return $this->container['battery_max_discharge_powerk_w'];
    }

    /**
     * Sets battery_max_discharge_powerk_w
     *
     * @param float $battery_max_discharge_powerk_w Gets the static 'nominal' maximum discharge power theoretically supported by the site's inverter and batteries. The actual \"at this point in time\" value may be lower. Unit: kilowatt
     *
     * @return $this
     */
    public function setBatteryMaxDischargePowerkW($battery_max_discharge_powerk_w)
    {
        $this->container['battery_max_discharge_powerk_w'] = $battery_max_discharge_powerk_w;

        return $this;
    }

    /**
     * Gets battery_capacityk_wh
     *
     * @return float
     */
    public function getBatteryCapacitykWh()
    {
        return $this->container['battery_capacityk_wh'];
    }

    /**
     * Sets battery_capacityk_wh
     *
     * @param float $battery_capacityk_wh Gets the size of the batteries.  Unit: kilowatthour
     *
     * @return $this
     */
    public function setBatteryCapacitykWh($battery_capacityk_wh)
    {
        $this->container['battery_capacityk_wh'] = $battery_capacityk_wh;

        return $this;
    }

    /**
     * Gets usable_battery_capacityk_wh
     *
     * @return float
     */
    public function getUsableBatteryCapacitykWh()
    {
        return $this->container['usable_battery_capacityk_wh'];
    }

    /**
     * Sets usable_battery_capacityk_wh
     *
     * @param float $usable_battery_capacityk_wh Gets the usable static nominal energy of the batteries. It is BatteryCapacitykWh x (1 - Nominal Min SoC). The actual \"at this point in time\" value may be lower and will be affected by the current SoC and by the 'reserve' Min SoC, which is usually higher than Battery Nominal Min SoC Unit: kilowatthour
     *
     * @return $this
     */
    public function setUsableBatteryCapacitykWh($usable_battery_capacityk_wh)
    {
        $this->container['usable_battery_capacityk_wh'] = $usable_battery_capacityk_wh;

        return $this;
    }

    /**
     * Gets panel_model
     *
     * @return string
     */
    public function getPanelModel()
    {
        return $this->container['panel_model'];
    }

    /**
     * Sets panel_model
     *
     * @param string $panel_model Gets the manufacturer and model of the panels
     *
     * @return $this
     */
    public function setPanelModel($panel_model)
    {
        $this->container['panel_model'] = $panel_model;

        return $this;
    }

    /**
     * Gets panel_sizek_w
     *
     * @return float
     */
    public function getPanelSizekW()
    {
        return $this->container['panel_sizek_w'];
    }

    /**
     * Sets panel_sizek_w
     *
     * @param float $panel_sizek_w Gets the total PV size. Unit: kilowatt
     *
     * @return $this
     */
    public function setPanelSizekW($panel_sizek_w)
    {
        $this->container['panel_sizek_w'] = $panel_sizek_w;

        return $this;
    }

    /**
     * Gets system_type
     *
     * @return string
     */
    public function getSystemType()
    {
        return $this->container['system_type'];
    }

    /**
     * Sets system_type
     *
     * @param string $system_type Gets System type
     *
     * @return $this
     */
    public function setSystemType($system_type)
    {
        $this->container['system_type'] = $system_type;

        return $this;
    }

    /**
     * Gets inverter_max_export_powerk_w
     *
     * @return float
     */
    public function getInverterMaxExportPowerkW()
    {
        return $this->container['inverter_max_export_powerk_w'];
    }

    /**
     * Sets inverter_max_export_powerk_w
     *
     * @param float $inverter_max_export_powerk_w Gets the static 'nominal' maximum export power. The actual \"at this point in time\" value may be lower, affected, for example by site export limit. Unit: kilowatt
     *
     * @return $this
     */
    public function setInverterMaxExportPowerkW($inverter_max_export_powerk_w)
    {
        $this->container['inverter_max_export_powerk_w'] = $inverter_max_export_powerk_w;

        return $this;
    }

    /**
     * Gets inverter_max_import_powerk_w
     *
     * @return float
     */
    public function getInverterMaxImportPowerkW()
    {
        return $this->container['inverter_max_import_powerk_w'];
    }

    /**
     * Sets inverter_max_import_powerk_w
     *
     * @param float $inverter_max_import_powerk_w Gets the static 'nominal' maximum input power. The actual \"at this point in time\" value may be lower. Unit: kilowatt
     *
     * @return $this
     */
    public function setInverterMaxImportPowerkW($inverter_max_import_powerk_w)
    {
        $this->container['inverter_max_import_powerk_w'] = $inverter_max_import_powerk_w;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
