<?php
/**
 * CreateScheduleRequestBySerialNumberDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * CreateScheduleRequestBySerialNumberDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Create Schedule Request
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateScheduleRequestBySerialNumberDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateScheduleRequestBySerialNumberDto"
     */
    public function testCreateScheduleRequestBySerialNumberDto()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "user_notes"
     */
    public function testPropertyUserNotes()
    {
    }

    /**
     * Test attribute "start_time_utc"
     */
    public function testPropertyStartTimeUtc()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "desired_mode"
     */
    public function testPropertyDesiredMode()
    {
    }
}
