<?php
/**
 * CreateOperatingEnvelopeWithGroupRequestDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * CreateOperatingEnvelopeWithGroupRequestDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Create Operting Envelope request
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateOperatingEnvelopeWithGroupRequestDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateOperatingEnvelopeWithGroupRequestDto"
     */
    public function testCreateOperatingEnvelopeWithGroupRequestDto()
    {
    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {
    }

    /**
     * Test attribute "start_at_utc"
     */
    public function testPropertyStartAtUtc()
    {
    }

    /**
     * Test attribute "end_at_utc"
     */
    public function testPropertyEndAtUtc()
    {
    }

    /**
     * Test attribute "max_import_power_w"
     */
    public function testPropertyMaxImportPowerW()
    {
    }

    /**
     * Test attribute "max_export_power_w"
     */
    public function testPropertyMaxExportPowerW()
    {
    }

    /**
     * Test attribute "max_discharge_power_w"
     */
    public function testPropertyMaxDischargePowerW()
    {
    }

    /**
     * Test attribute "max_charge_power_w"
     */
    public function testPropertyMaxChargePowerW()
    {
    }

    /**
     * Test attribute "max_generation_power_va"
     */
    public function testPropertyMaxGenerationPowerVa()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }
}
