<?php
/**
 * InverterSiteDynamicDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InverterSiteDynamicDataTest Class Doc Comment
 *
 * @category    Class
 * @description Dynamic data for an inverter site for API version prior to 2.19
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InverterSiteDynamicDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InverterSiteDynamicData"
     */
    public function testInverterSiteDynamicData()
    {
    }

    /**
     * Test attribute "timestamp_utc"
     */
    public function testPropertyTimestampUtc()
    {
    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {
    }

    /**
     * Test attribute "phases"
     */
    public function testPropertyPhases()
    {
    }

    /**
     * Test attribute "frequency_instantaneous_hz"
     */
    public function testPropertyFrequencyInstantaneousHz()
    {
    }

    /**
     * Test attribute "battery_so_c_instantaneous0to1"
     */
    public function testPropertyBatterySoCInstantaneous0to1()
    {
    }

    /**
     * Test attribute "pv_power_instantaneousk_w"
     */
    public function testPropertyPvPowerInstantaneouskW()
    {
    }

    /**
     * Test attribute "inverter_temperature_c"
     */
    public function testPropertyInverterTemperatureC()
    {
    }

    /**
     * Test attribute "battery_power_negative_is_chargingk_w"
     */
    public function testPropertyBatteryPowerNegativeIsChargingkW()
    {
    }

    /**
     * Test attribute "pv_all_time_energyk_wh"
     */
    public function testPropertyPvAllTimeEnergykWh()
    {
    }

    /**
     * Test attribute "export_all_time_energyk_wh"
     */
    public function testPropertyExportAllTimeEnergykWh()
    {
    }

    /**
     * Test attribute "import_all_time_energyk_wh"
     */
    public function testPropertyImportAllTimeEnergykWh()
    {
    }

    /**
     * Test attribute "load_all_time_energyk_wh"
     */
    public function testPropertyLoadAllTimeEnergykWh()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "inverters"
     */
    public function testPropertyInverters()
    {
    }
}
