<?php
/**
 * InverterConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InverterConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description Inverter configuration
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InverterConfigurationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InverterConfiguration"
     */
    public function testInverterConfiguration()
    {
    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {
    }

    /**
     * Test attribute "nmi"
     */
    public function testPropertyNmi()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "generation_hard_limit_va"
     */
    public function testPropertyGenerationHardLimitVa()
    {
    }

    /**
     * Test attribute "generation_soft_limit_va"
     */
    public function testPropertyGenerationSoftLimitVa()
    {
    }

    /**
     * Test attribute "export_hard_limitk_w"
     */
    public function testPropertyExportHardLimitkW()
    {
    }

    /**
     * Test attribute "export_soft_limitk_w"
     */
    public function testPropertyExportSoftLimitkW()
    {
    }

    /**
     * Test attribute "site_export_limitk_w"
     */
    public function testPropertySiteExportLimitkW()
    {
    }

    /**
     * Test attribute "battery_max_charge_powerk_w"
     */
    public function testPropertyBatteryMaxChargePowerkW()
    {
    }

    /**
     * Test attribute "battery_max_discharge_powerk_w"
     */
    public function testPropertyBatteryMaxDischargePowerkW()
    {
    }

    /**
     * Test attribute "battery_capacityk_wh"
     */
    public function testPropertyBatteryCapacitykWh()
    {
    }

    /**
     * Test attribute "usable_battery_capacityk_wh"
     */
    public function testPropertyUsableBatteryCapacitykWh()
    {
    }

    /**
     * Test attribute "system_type"
     */
    public function testPropertySystemType()
    {
    }

    /**
     * Test attribute "inverter_max_export_powerk_w"
     */
    public function testPropertyInverterMaxExportPowerkW()
    {
    }

    /**
     * Test attribute "inverter_max_import_powerk_w"
     */
    public function testPropertyInverterMaxImportPowerkW()
    {
    }

    /**
     * Test attribute "min_so_c0to1"
     */
    public function testPropertyMinSoC0to1()
    {
    }

    /**
     * Test attribute "min_offgrid_so_c0to1"
     */
    public function testPropertyMinOffgridSoC0to1()
    {
    }
}
