<?php
/**
 * InverterSiteStaticDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InverterSiteStaticDataTest Class Doc Comment
 *
 * @category    Class
 * @description Inverter Site Static Data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InverterSiteStaticDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InverterSiteStaticData"
     */
    public function testInverterSiteStaticData()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "dynamic_data_metadata"
     */
    public function testPropertyDynamicDataMetadata()
    {
    }

    /**
     * Test attribute "timestamp_utc"
     */
    public function testPropertyTimestampUtc()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "technology_provider"
     */
    public function testPropertyTechnologyProvider()
    {
    }

    /**
     * Test attribute "remote_access_connection"
     */
    public function testPropertyRemoteAccessConnection()
    {
    }

    /**
     * Test attribute "approved_capacity_w"
     */
    public function testPropertyApprovedCapacityW()
    {
    }

    /**
     * Test attribute "solar_retailer"
     */
    public function testPropertySolarRetailer()
    {
    }

    /**
     * Test attribute "site_details"
     */
    public function testPropertySiteDetails()
    {
    }

    /**
     * Test attribute "commissioning_date"
     */
    public function testPropertyCommissioningDate()
    {
    }

    /**
     * Test attribute "nmi"
     */
    public function testPropertyNmi()
    {
    }

    /**
     * Test attribute "latest_dynamic_data_utc"
     */
    public function testPropertyLatestDynamicDataUtc()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
