<?php
/**
 * OperatingEnvelopeComplianceReportRowTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * OperatingEnvelopeComplianceReportRowTest Class Doc Comment
 *
 * @category    Class
 * @description Data describing a single system in the compliance report
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OperatingEnvelopeComplianceReportRowTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OperatingEnvelopeComplianceReportRow"
     */
    public function testOperatingEnvelopeComplianceReportRow()
    {
    }

    /**
     * Test attribute "nmi"
     */
    public function testPropertyNmi()
    {
    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {
    }

    /**
     * Test attribute "site_power_w"
     */
    public function testPropertySitePowerW()
    {
    }

    /**
     * Test attribute "last_connection_utc"
     */
    public function testPropertyLastConnectionUtc()
    {
    }

    /**
     * Test attribute "address_line_one"
     */
    public function testPropertyAddressLineOne()
    {
    }

    /**
     * Test attribute "address_line_two"
     */
    public function testPropertyAddressLineTwo()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "post_code"
     */
    public function testPropertyPostCode()
    {
    }

    /**
     * Test attribute "suburb"
     */
    public function testPropertySuburb()
    {
    }

    /**
     * Test attribute "site_export_limit_enabled"
     */
    public function testPropertySiteExportLimitEnabled()
    {
    }

    /**
     * Test attribute "site_export_limit_w"
     */
    public function testPropertySiteExportLimitW()
    {
    }

    /**
     * Test attribute "is_disconnected"
     */
    public function testPropertyIsDisconnected()
    {
    }

    /**
     * Test attribute "is_online"
     */
    public function testPropertyIsOnline()
    {
    }

    /**
     * Test attribute "generation_status"
     */
    public function testPropertyGenerationStatus()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }
}
