<?php
/**
 * PhaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PhaseTest Class Doc Comment
 *
 * @category    Class
 * @description Phase
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PhaseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Phase"
     */
    public function testPhase()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "active_exported_power_instantaneousk_w"
     */
    public function testPropertyActiveExportedPowerInstantaneouskW()
    {
    }

    /**
     * Test attribute "active_imported_power_instantaneousk_w"
     */
    public function testPropertyActiveImportedPowerInstantaneouskW()
    {
    }

    /**
     * Test attribute "voltage_instantaneous_v"
     */
    public function testPropertyVoltageInstantaneousV()
    {
    }

    /**
     * Test attribute "current_instantaneous_a"
     */
    public function testPropertyCurrentInstantaneousA()
    {
    }

    /**
     * Test attribute "power_factor_instantaneous_minus1to1"
     */
    public function testPropertyPowerFactorInstantaneousMinus1to1()
    {
    }
}
