<?php
/**
 * ScheduleDaysTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ScheduleDaysTest Class Doc Comment
 *
 * @category    Class
 * @description Schedule days flags. Bit flags.  Examples: A. a) 1 or b) \&quot;Sunday\&quot; means Sunday B. a) 5 or b) \&quot;Monday, Wednesday\&quot; means Monday and Wednesday C. a) 62 or b) \&quot;Weekdays\&quot; or c) \&quot;Monday, Tuesday, Wednesday, Thursday, Friday\&quot; means Monday to Fridays inclusive.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduleDaysTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScheduleDays"
     */
    public function testScheduleDays()
    {
    }
}
