<?php
/**
 * ConfigurationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redback API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: ITOps@redbacktech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConfigurationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for configurationGetConfiguration
     *
     * Gets configuration data for a site..
     *
     */
    public function testConfigurationGetConfiguration()
    {
    }

    /**
     * Test case for configurationGetConfigurationByNmi
     *
     * Gets configuration data for a site..
     *
     */
    public function testConfigurationGetConfigurationByNmi()
    {
    }

    /**
     * Test case for configurationGetConfigurationByNmi2
     *
     * Gets configuration data..
     *
     */
    public function testConfigurationGetConfigurationByNmi2()
    {
    }

    /**
     * Test case for configurationGetConfigurationBySerialNumber
     *
     * Gets configuration data got an inverter..
     *
     */
    public function testConfigurationGetConfigurationBySerialNumber()
    {
    }

    /**
     * Test case for configurationGetConfigurationBySerialNumberMultiple
     *
     * Gets configuration data..
     *
     */
    public function testConfigurationGetConfigurationBySerialNumberMultiple()
    {
    }

    /**
     * Test case for configurationGetConfigurationMultiple
     *
     * Gets configuration data..
     *
     */
    public function testConfigurationGetConfigurationMultiple()
    {
    }
}
